# Build settings

markdown: kramdown
permalink: pretty


port: 2000


sass:
  sass_dir: assets/css
  style: :nested


baseurl: /FrontFolio


# fall back javascript disable
projectNoscript: >
  ** No javscript babe!

